version: 2
enable-beta-ecosystems: true
updates:
  - directories:
      - /
      - apps/**
      - packages/**
    open-pull-requests-limit: 5
    rebase-strategy: auto
    package-ecosystem: npm
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    assignees:
      - ajhalili2006
  - directory: /
    open-pull-requests-limit: 2
    rebase-strategy: auto
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    assignees:
      - ajhalili2006
