// Generated by Wrangler on Wed Jul 17 2024 01:25:40 GMT+0800 (Philippine Standard Time)
// by running `wrangler types`

export interface Env {
	DEPLOY_ENV: 'production' | 'staging' | 'development';
	golinks: D1Database;
}
