#:schema ../../node_modules/wrangler/config-schema.json

# This is the Wrangler configuration for golinks-next, and is being used
# in GitHub Actions and/or GitLab CI for automatic deployments to
# staging and production. If you are testing this in a devenv or want
# to run a copy of this on your own Cloudflare account, you need to update
# the account ID and database IDs in the D1 database bindings for staging
# and production environments.

name = "golinks-next"
main = "src/index.ts"
compatibility_date = "2024-07-12" # TODO: Update this once a month.
account_id = "cf0bd808c6a294fd8c4d8f6d2cdeca05"

placement = { mode = "smart" }

vars = {DEPLOY_ENV = "development", ADMIN_KEY = "gostg_localdev"}

d1_databases = [
	{ binding = "golinks", database_name = "golinks-db-preview", database_id = "0b415a64-cc61-4c2b-a7c8-2d223f18e996", migrations_dir = "migrations" }
]

[env.staging]
vars = {DEPLOY_ENV = "staging", ADMIN_KEY = "GOLINKS_ADMIN_API_KEY"}

d1_databases = [
	{ binding = "golinks", database_name = "golinks-db-preview", database_id = "0b415a64-cc61-4c2b-a7c8-2d223f18e996", migrations_dir = "migrations" }
]



[env.production]
vars = {DEPLOY_ENV = "production", ADMIN_KEY = "GOLINKS_ADMIN_API_KEY"}

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
d1_databases = [
	{ binding = "golinks", database_name = "golinks-db", database_id = "63e746f4-40de-4f8c-a3e5-7969cde040b3", migrations_dir = "migrations"}
]
