#:schema ../../node_modules/wrangler/config-schema.json

# This is the Wrangler configuration for golinks-next, and is being used
# in GitHub Actions and/or GitLab CI for automatic deployments to
# staging and production. If you are testing this in a devenv or want
# to run a copy of this on your own Cloudflare account, you need to update
# the account ID and database IDs in the D1 database bindings for staging
# and production environments.

name = "golinks-next"
main = "src/index.tsx"
compatibility_date = "2024-07-12"               # TODO: Update this once a month.
account_id = "cf0bd808c6a294fd8c4d8f6d2cdeca05"

placement = { mode = "smart" }
node_compat = true

# Please do not leak your secrets here.
vars = { DEPLOY_ENV = "development", ADMIN_KEY = "gostg_localdev-null", BASE_URL = "https://stellapent-cier.fawn-cod.ts.net" }

d1_databases = [
    { binding = "golinks", database_name = "golinks-db-preview", database_id = "0b415a64-cc61-4c2b-a7c8-2d223f18e996", migrations_dir = "migrations" },
]
kv_namespaces = [
	{ binding = "slackBotTokens", id = "24a1f8bb9d434e97a490c43b74435e64" }
]

[env.staging]
workers_dev = true
vars = { DEPLOY_ENV = "staging", BASE_URL = "https://staging.go-next.andreijiroh.xyz" }
d1_databases = [
    { binding = "golinks", database_name = "golinks-db-preview", database_id = "0b415a64-cc61-4c2b-a7c8-2d223f18e996", migrations_dir = "migrations" },
]
kv_namespaces = [
	{ binding = "slackBotTokens", id = "24a1f8bb9d434e97a490c43b74435e64" }
]
routes = [
    { custom_domain = true, pattern = "staging.go-next.andreijiroh.xyz", zone_name = "andreijiroh.xyz" },
    { custom_domain = true, pattern = "go-next.andreijiroh.xyz", zone_name = "andreijiroh.xyz" },
]

[env.production]
workers_dev = true
vars = { DEPLOY_ENV = "production", BASE_URL = "https://go.andreijiroh.xyz" }
d1_databases = [
    { binding = "golinks", database_name = "golinks-db", database_id = "63e746f4-40de-4f8c-a3e5-7969cde040b3", migrations_dir = "migrations" },
]
kv_namespaces = [
	{ binding = "slackBotTokens", id = "21b6d6aaacbf4f04b52a66a9ed11fcd3" }
]
routes = [
    { pattern = "go.andreijiroh.xyz", zone_name = "andreijiroh.xyz", custom_domain = true },
    # Inspired by @flanican's website on adding /go/ links to
    # both my website and in the wiki.
    { pattern = "wiki.andreijiroh.xyz/go/*", zone_name = "andreijiroh.xyz" },
    { pattern = "andreijiroh.xyz/go/*", zone_name = "andreijiroh.xyz" },
]
