#:schema ../../node_modules/wrangler/config-schema.json
name = "golinks-next"
main = "src/index.ts"
compatibility_date = "2024-07-12"

[placement]
mode = "smart"

vars = {DEPLOY_ENV = "development"}

d1_databases = [
	{ binding = "golinks", database_name = "golinks-db-preview", database_id = "0b415a64-cc61-4c2b-a7c8-2d223f18e996", migrations_dir = "migrations" }
]

[env.staging]
vars = {DEPLOY_ENV = "staging"}

d1_databases = [
	{ binding = "golinks", database_name = "golinks-db-preview", database_id = "0b415a64-cc61-4c2b-a7c8-2d223f18e996", migrations_dir = "migrations" }
]

[env.production]
vars = {DEPLOY_ENV = "production"}

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
d1_databases = [
	{ binding = "golinks", database_name = "golinks-db", database_id = "63e746f4-40de-4f8c-a3e5-7969cde040b3", migrations_dir = "migrations"}
]
