// Generated by Wrangler on Thu Jul 18 2024 01:03:07 GMT+0800 (Philippine Standard Time)
// by running `wrangler types --env staging`

interface Env {
  DEPLOY_ENV: "staging";
  ADMIN_KEY: "GOLINKS_ADMIN_API_KEY";
  golinks: D1Database;
}
